# Generated by Django 3.2.6 on 2021-08-31 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='officeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=150)),
                ('empdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_shared.empdetails')),
            ],
        ),
    ]
